// <auto-generated />
using System;
using Entities.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HostApp.Migrations
{
    [DbContext(typeof(DAL))]
    [Migration("20201018205031_orderInputParam")]
    partial class orderInputParam
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.ActionType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_jsonForm")
                        .HasColumnName("Form")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("ActionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Gagnez un point de Stratégie",
                            GameId = 1L,
                            Label = "Planification",
                            _jsonForm = "[{\"Label\":\"Augmentation\",\"Type\":\"Checkbox\",\"Description\":\"Manoeuvre sournoise : Gagnez 2 points d\\u0027Infamie pour gagner un point de Strat\\u00E9gie suppl\\u00E9mentaire\",\"Parameter\":null}]"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Gagnez 2 points de Gloire et faites-en gagner 2 à un adversaire",
                            GameId = 1L,
                            Label = "Flatterie",
                            _jsonForm = "[{\"Label\":\"Cible\",\"Type\":\"Opponent\",\"Description\":\"L\\u0027adversaire recevant 2 points de Gloire\",\"Parameter\":null},{\"Label\":\"Augmentation\",\"Type\":\"Checkbox\",\"Description\":\"Faveur politique : D\\u00E9pensez un point d\\u2019Influence pour gagner 3 points de Gloire suppl\\u00E9mentaires et ne cibler personne\",\"Parameter\":null}]"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Infligez 3 points d’Infamie à un adversaire et gagnez-en vous-même un point",
                            GameId = 1L,
                            Label = "Médisance",
                            _jsonForm = "[{\"Label\":\"Cible\",\"Type\":\"Opponent\",\"Description\":\"L\\u0027adversaire subissant la m\\u00E9disance\",\"Parameter\":null},{\"Label\":\"Augmentation\",\"Type\":\"Checkbox\",\"Description\":\"Scandale : D\\u00E9pensez un point d\\u2019Influence pour ajouter 2 points d\\u2019Infamie \\u00E0 votre cible et remplacer votre gain d\\u0027Infamie par un gain de Gloire.\",\"Parameter\":null}]"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Déployez une armée pour 5 points de Stratégie",
                            GameId = 1L,
                            Label = "Renforts",
                            _jsonForm = "[{\"Label\":\"Case\",\"Type\":\"EntryTile\",\"Description\":\"La case de renfort cibl\\u00E9e\",\"Parameter\":null},{\"Label\":\"Formation\",\"Type\":\"Formation\",\"Description\":\"La formation \\u00E0 adopter\",\"Parameter\":null},{\"Label\":\"Augmentation\",\"Type\":\"Checkbox\",\"Description\":\"Soutien militaire : D\\u00E9pensez un point d\\u0027Influence \\u00E0 la place des points de Strat\\u00E9gie.\",\"Parameter\":null}]"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Déplacez une armée d'une case",
                            GameId = 1L,
                            Label = "Déplacement",
                            _jsonForm = "[{\"Label\":\"Arm\\u00E9e\",\"Type\":\"Army\",\"Description\":\"L\\u0027arm\\u00E9e \\u00E0 d\\u00E9placer\",\"Parameter\":null},{\"Label\":\"Destination\",\"Type\":\"Move\",\"Description\":\"La destination de l\\u0027arm\\u00E9e\",\"Parameter\":\"Arm\\u00E9e\"},{\"Label\":\"Augmentation\",\"Type\":\"Checkbox\",\"Description\":\"Ligne de ravitaillement : D\\u00E9pensez un point d\\u0027Influence pour d\\u00E9placer l\\u0027arm\\u00E9e apr\\u00E8s un renfort ou un changement de formation.\",\"Parameter\":null}]"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Changez la formation de l'armée",
                            GameId = 1L,
                            Label = "Formation",
                            _jsonForm = "[{\"Label\":\"Arm\\u00E9e\",\"Type\":\"Army\",\"Description\":\"L\\u0027arm\\u00E9e cibl\\u00E9e\",\"Parameter\":null},{\"Label\":\"Formation\",\"Type\":\"Formation\",\"Description\":\"La formation \\u00E0 adopter\",\"Parameter\":\"Arm\\u00E9e\"},{\"Label\":\"Augmentation\",\"Type\":\"Checkbox\",\"Description\":\"Discipline : D\\u00E9pensez un point de Strat\\u00E9gie pour changer de formation apr\\u00E8s un d\\u00E9placement.\",\"Parameter\":null}]"
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Subissez un point d'Infamie pour espionner un adversaire",
                            GameId = 1L,
                            Label = "Renseignements",
                            _jsonForm = "[{\"Label\":\"Cible\",\"Type\":\"Opponent\",\"Description\":\"L\\u0027adversaire \\u00E0 espionner\",\"Parameter\":null},{\"Label\":\"Augmentation\",\"Type\":\"Checkbox\",\"Description\":\"R\\u00E9seau d\\u0027information : D\\u00E9pensez un point d\\u0027Influence pour annuler l\\u0027Infamie et cibler tous les adversaires.\",\"Parameter\":null}]"
                        });
                });

            modelBuilder.Entity("Entities.Models.Campaign", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentPhase")
                        .HasColumnType("int");

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("int");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NextPhase")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhaseLength")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("_jsonAssets")
                        .HasColumnName("Assets")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CurrentPhase = 2,
                            CurrentTurn = 1,
                            GameId = 1L,
                            Name = "La bataille des Quatre Vents",
                            NextPhase = new DateTime(2020, 10, 19, 22, 50, 31, 148, DateTimeKind.Local).AddTicks(8986),
                            PhaseLength = 1440,
                            Status = 2,
                            _jsonAssets = "{\"Classement\":{\"1er\":\"Doji Misao\",\"2\\u00E8me\":\"Kitsuki Hisao\",\"3\\u00E8me\":\"Yogo Rushi\",\"4\\u00E8me\":\"Ikoma Kiyoshi\"},\"Prochain classement\":{\"Tour 6\":\"\"}}"
                        });
                });

            modelBuilder.Entity("Entities.Models.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_jsonHomeWidgets")
                        .HasColumnName("HomeWidgets")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "L5A Strat - TERRE",
                            _jsonHomeWidgets = "[\"Clock\",\"PlayerInfo\",\"CampaignInfo\"]"
                        });
                });

            modelBuilder.Entity("Entities.Models.Map", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Turn")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Maps");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CampaignId = 1L,
                            CreationDate = new DateTime(2020, 10, 18, 22, 50, 31, 163, DateTimeKind.Local).AddTicks(9757),
                            Name = "Début de Tour 1",
                            PlayerId = 1L,
                            Turn = 1
                        });
                });

            modelBuilder.Entity("Entities.Models.MapTile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MapId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<string>("_jsonAssets")
                        .HasColumnName("Assets")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("MapTiles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (A1)",
                            Symbol = "",
                            X = 0,
                            Y = 0,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 2L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (A2)",
                            Symbol = "",
                            X = 0,
                            Y = 1,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 3L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (A3)",
                            Symbol = "",
                            X = 0,
                            Y = 2,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 4L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Entrée (A4)",
                            Symbol = "home",
                            X = 0,
                            Y = 3,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Kitsuki Hisao\":\"\"}}"
                        },
                        new
                        {
                            Id = 5L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Entrée (A5)",
                            Symbol = "home",
                            X = 0,
                            Y = 4,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Kitsuki Hisao\":\"\"}}"
                        },
                        new
                        {
                            Id = 6L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Entrée (A6)",
                            Symbol = "home",
                            X = 0,
                            Y = 5,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Kitsuki Hisao\":\"\"}}"
                        },
                        new
                        {
                            Id = 7L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Entrée (A7)",
                            Symbol = "home",
                            X = 0,
                            Y = 6,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Kitsuki Hisao\":\"\"}}"
                        },
                        new
                        {
                            Id = 8L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (A8)",
                            Symbol = "",
                            X = 0,
                            Y = 7,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 9L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (A9)",
                            Symbol = "",
                            X = 0,
                            Y = 8,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 10L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (B1)",
                            Symbol = "",
                            X = 1,
                            Y = 0,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 11L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Avant-poste (B2)",
                            Symbol = "tower",
                            X = 1,
                            Y = 1,
                            _jsonAssets = "{\"Production\":{\"Gloire\":\"1\",\"Strat\\u00E9gie\":\"2\"}}"
                        },
                        new
                        {
                            Id = 12L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (B3)",
                            Symbol = "",
                            X = 1,
                            Y = 2,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 13L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (B4)",
                            Symbol = "",
                            X = 1,
                            Y = 3,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 14L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (B5)",
                            Symbol = "",
                            X = 1,
                            Y = 4,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 15L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (B6)",
                            Symbol = "",
                            X = 1,
                            Y = 5,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 16L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (B7)",
                            Symbol = "",
                            X = 1,
                            Y = 6,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 17L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (B8)",
                            Symbol = "",
                            X = 1,
                            Y = 7,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 18L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (B9)",
                            Symbol = "",
                            X = 1,
                            Y = 8,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 19L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (C1)",
                            Symbol = "",
                            X = 2,
                            Y = 0,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 20L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (C2)",
                            Symbol = "",
                            X = 2,
                            Y = 1,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 21L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (C3)",
                            Symbol = "",
                            X = 2,
                            Y = 2,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 22L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Village (C4)",
                            Symbol = "house",
                            X = 2,
                            Y = 3,
                            _jsonAssets = "{\"Production\":{\"Gloire\":\"2\"}}"
                        },
                        new
                        {
                            Id = 23L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (C5)",
                            Symbol = "",
                            X = 2,
                            Y = 4,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 24L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (C6)",
                            Symbol = "",
                            X = 2,
                            Y = 5,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 25L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (C7)",
                            Symbol = "",
                            X = 2,
                            Y = 6,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 26L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (C8)",
                            Symbol = "",
                            X = 2,
                            Y = 7,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 27L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Entrée (C9)",
                            Symbol = "home",
                            X = 2,
                            Y = 8,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Yogo Rushi\":\"\"}}"
                        },
                        new
                        {
                            Id = 28L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Entrée (D1)",
                            Symbol = "home",
                            X = 3,
                            Y = 0,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Ikoma Kiyoshi\":\"\"}}"
                        },
                        new
                        {
                            Id = 29L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (D2)",
                            Symbol = "",
                            X = 3,
                            Y = 1,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 30L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (D3)",
                            Symbol = "",
                            X = 3,
                            Y = 2,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 31L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (D4)",
                            Symbol = "",
                            X = 3,
                            Y = 3,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 32L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (D5)",
                            Symbol = "",
                            X = 3,
                            Y = 4,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 33L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (D6)",
                            Symbol = "",
                            X = 3,
                            Y = 5,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 34L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Village (D7)",
                            Symbol = "house",
                            X = 3,
                            Y = 6,
                            _jsonAssets = "{\"Production\":{\"Gloire\":\"2\"}}"
                        },
                        new
                        {
                            Id = 35L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (D8)",
                            Symbol = "",
                            X = 3,
                            Y = 7,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 36L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Entrée (D9)",
                            Symbol = "home",
                            X = 3,
                            Y = 8,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Yogo Rushi\":\"\"}}"
                        },
                        new
                        {
                            Id = 37L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Entrée (E1)",
                            Symbol = "home",
                            X = 4,
                            Y = 0,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Ikoma Kiyoshi\":\"\"}}"
                        },
                        new
                        {
                            Id = 38L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (E2)",
                            Symbol = "",
                            X = 4,
                            Y = 1,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 39L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (E3)",
                            Symbol = "",
                            X = 4,
                            Y = 2,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 40L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (E4)",
                            Symbol = "",
                            X = 4,
                            Y = 3,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 41L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Forteresse (E5)",
                            Symbol = "castle",
                            X = 4,
                            Y = 4,
                            _jsonAssets = "{\"Production\":{\"Gloire\":\"3\",\"Strat\\u00E9gie\":\"2\"}}"
                        },
                        new
                        {
                            Id = 42L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (E6)",
                            Symbol = "",
                            X = 4,
                            Y = 5,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 43L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (E7)",
                            Symbol = "",
                            X = 4,
                            Y = 6,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 44L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (E8)",
                            Symbol = "",
                            X = 4,
                            Y = 7,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 45L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Entrée (E9)",
                            Symbol = "home",
                            X = 4,
                            Y = 8,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Yogo Rushi\":\"\"}}"
                        },
                        new
                        {
                            Id = 46L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Entrée (F1)",
                            Symbol = "home",
                            X = 5,
                            Y = 0,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Ikoma Kiyoshi\":\"\"}}"
                        },
                        new
                        {
                            Id = 47L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (F2)",
                            Symbol = "",
                            X = 5,
                            Y = 1,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 48L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Village (F3)",
                            Symbol = "house",
                            X = 5,
                            Y = 2,
                            _jsonAssets = "{\"Production\":{\"Gloire\":\"2\"}}"
                        },
                        new
                        {
                            Id = 49L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (F4)",
                            Symbol = "",
                            X = 5,
                            Y = 3,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 50L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (F5)",
                            Symbol = "",
                            X = 5,
                            Y = 4,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 51L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (F6)",
                            Symbol = "",
                            X = 5,
                            Y = 5,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 52L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (F7)",
                            Symbol = "",
                            X = 5,
                            Y = 6,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 53L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (F8)",
                            Symbol = "",
                            X = 5,
                            Y = 7,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 54L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Entrée (F9)",
                            Symbol = "home",
                            X = 5,
                            Y = 8,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Yogo Rushi\":\"\"}}"
                        },
                        new
                        {
                            Id = 55L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Entrée (G1)",
                            Symbol = "home",
                            X = 6,
                            Y = 0,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Ikoma Kiyoshi\":\"\"}}"
                        },
                        new
                        {
                            Id = 56L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (G2)",
                            Symbol = "",
                            X = 6,
                            Y = 1,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 57L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (G3)",
                            Symbol = "",
                            X = 6,
                            Y = 2,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 58L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (G4)",
                            Symbol = "",
                            X = 6,
                            Y = 3,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 59L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (G5)",
                            Symbol = "",
                            X = 6,
                            Y = 4,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 60L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Village (G6)",
                            Symbol = "house",
                            X = 6,
                            Y = 5,
                            _jsonAssets = "{\"Production\":{\"Gloire\":\"2\"}}"
                        },
                        new
                        {
                            Id = 61L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (G7)",
                            Symbol = "",
                            X = 6,
                            Y = 6,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 62L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (G8)",
                            Symbol = "",
                            X = 6,
                            Y = 7,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 63L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (G9)",
                            Symbol = "",
                            X = 6,
                            Y = 8,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 64L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (H1)",
                            Symbol = "",
                            X = 7,
                            Y = 0,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 65L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (H2)",
                            Symbol = "",
                            X = 7,
                            Y = 1,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 66L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (H3)",
                            Symbol = "",
                            X = 7,
                            Y = 2,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 67L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (H4)",
                            Symbol = "",
                            X = 7,
                            Y = 3,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 68L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (H5)",
                            Symbol = "",
                            X = 7,
                            Y = 4,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 69L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (H6)",
                            Symbol = "",
                            X = 7,
                            Y = 5,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 70L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (H7)",
                            Symbol = "",
                            X = 7,
                            Y = 6,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 71L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Avant-poste (H8)",
                            Symbol = "tower",
                            X = 7,
                            Y = 7,
                            _jsonAssets = "{\"Production\":{\"Gloire\":\"1\",\"Strat\\u00E9gie\":\"2\"}}"
                        },
                        new
                        {
                            Id = 72L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (H9)",
                            Symbol = "",
                            X = 7,
                            Y = 8,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 73L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (I1)",
                            Symbol = "",
                            X = 8,
                            Y = 0,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 74L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (I2)",
                            Symbol = "",
                            X = 8,
                            Y = 1,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 75L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Entrée (I3)",
                            Symbol = "home",
                            X = 8,
                            Y = 2,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Doji Misao\":\"\"}}"
                        },
                        new
                        {
                            Id = 76L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Entrée (I4)",
                            Symbol = "home",
                            X = 8,
                            Y = 3,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Doji Misao\":\"\"}}"
                        },
                        new
                        {
                            Id = 77L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Entrée (I5)",
                            Symbol = "home",
                            X = 8,
                            Y = 4,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Doji Misao\":\"\"}}"
                        },
                        new
                        {
                            Id = 78L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Entrée (I6)",
                            Symbol = "home",
                            X = 8,
                            Y = 5,
                            _jsonAssets = "{\"Propri\\u00E9taire\":{\"Doji Misao\":\"\"}}"
                        },
                        new
                        {
                            Id = 79L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (I7)",
                            Symbol = "",
                            X = 8,
                            Y = 6,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 80L,
                            Color = "linen",
                            MapId = 1L,
                            Name = "Plaine (I8)",
                            Symbol = "",
                            X = 8,
                            Y = 7,
                            _jsonAssets = "{}"
                        },
                        new
                        {
                            Id = 81L,
                            Color = "wheat",
                            MapId = 1L,
                            Name = "Plaine (I9)",
                            Symbol = "",
                            X = 8,
                            Y = 8,
                            _jsonAssets = "{}"
                        });
                });

            modelBuilder.Entity("Entities.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ActionTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrdersSheetId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("_jsonParameters")
                        .HasColumnName("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("OrdersSheetId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActionTypeId = 1L,
                            Comment = "+ 1 Strat",
                            OrdersSheetId = 1L,
                            Rank = 0,
                            Status = 2,
                            _jsonParameters = "{\"Augmentation\":\"false\"}"
                        },
                        new
                        {
                            Id = 2L,
                            ActionTypeId = 2L,
                            Comment = "+ 2 Gloire, Yogo Rushi + 2 Gloire",
                            OrdersSheetId = 2L,
                            Rank = 0,
                            Status = 2,
                            _jsonParameters = "{\"Cible\":\"5\",\"Augmentation\":\"false\"}"
                        },
                        new
                        {
                            Id = 3L,
                            ActionTypeId = 4L,
                            Comment = "+ 1 Infamie, Doji Misao +3 Infamie",
                            OrdersSheetId = 3L,
                            Rank = 0,
                            Status = 2,
                            _jsonParameters = "{\"Cible\":\"3\",\"Augmentation\":\"false\"}"
                        },
                        new
                        {
                            Id = 4L,
                            ActionTypeId = 1L,
                            Comment = "+ 1 Strat",
                            OrdersSheetId = 4L,
                            Rank = 0,
                            Status = 2,
                            _jsonParameters = "{\"Augmentation\":\"false\"}"
                        });
                });

            modelBuilder.Entity("Entities.Models.OrdersSheet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxOrdersCount")
                        .HasColumnType("int");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Turn")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("OrdersSheets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MaxOrdersCount = 5,
                            PlayerId = 2L,
                            Priority = 0,
                            Status = 1,
                            Turn = 3
                        },
                        new
                        {
                            Id = 2L,
                            MaxOrdersCount = 5,
                            PlayerId = 3L,
                            Priority = 0,
                            Status = 1,
                            Turn = 3
                        },
                        new
                        {
                            Id = 3L,
                            MaxOrdersCount = 5,
                            PlayerId = 4L,
                            Priority = 0,
                            Status = 1,
                            Turn = 3
                        },
                        new
                        {
                            Id = 4L,
                            MaxOrdersCount = 5,
                            PlayerId = 5L,
                            Priority = 0,
                            Status = 1,
                            Turn = 3
                        });
                });

            modelBuilder.Entity("Entities.Models.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrentPlayer")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("_jsonAssets")
                        .HasColumnName("Assets")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CampaignId = 1L,
                            IsAdmin = true,
                            IsCurrentPlayer = true,
                            Name = "Admin",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CampaignId = 1L,
                            Color = "green",
                            IsAdmin = false,
                            IsCurrentPlayer = true,
                            Name = "Kitsuki Hisao",
                            UserId = 2L,
                            _jsonAssets = "{\"Caract\\u00E9ristiques\":{\"Gloire\":\"5\",\"Infamie\":\"1\"},\"Ressources\":{\"Strat\\u00E9gie\":\"3\",\"Influence\":\"0\"}}"
                        },
                        new
                        {
                            Id = 3L,
                            CampaignId = 1L,
                            Color = "cyan",
                            IsAdmin = false,
                            IsCurrentPlayer = true,
                            Name = "Doji Misao",
                            UserId = 3L,
                            _jsonAssets = "{\"Caract\\u00E9ristiques\":{\"Gloire\":\"7\",\"Infamie\":\"0\"},\"Ressources\":{\"Strat\\u00E9gie\":\"2\",\"Influence\":\"1\"}}"
                        },
                        new
                        {
                            Id = 4L,
                            CampaignId = 1L,
                            Color = "yellow",
                            IsAdmin = false,
                            IsCurrentPlayer = true,
                            Name = "Ikoma Kiyoshi",
                            UserId = 4L,
                            _jsonAssets = "{\"Caract\\u00E9ristiques\":{\"Gloire\":\"3\",\"Infamie\":\"0\"},\"Ressources\":{\"Strat\\u00E9gie\":\"5\",\"Influence\":\"0\"}}"
                        },
                        new
                        {
                            Id = 5L,
                            CampaignId = 1L,
                            Color = "red",
                            IsAdmin = false,
                            IsCurrentPlayer = true,
                            Name = "Yogo Rushi",
                            UserId = 5L,
                            _jsonAssets = "{\"Caract\\u00E9ristiques\":{\"Gloire\":\"4\",\"Infamie\":\"2\"},\"Ressources\":{\"Strat\\u00E9gie\":\"4\",\"Influence\":\"0\"}}"
                        });
                });

            modelBuilder.Entity("Entities.Models.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<string>("_jsonAssets")
                        .HasColumnName("Assets")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Forteresse",
                            PlayerId = 1L,
                            Type = "Building",
                            X = 4,
                            Y = 4,
                            _jsonAssets = "{\"Type\":{\"Forteresse\":null}}"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Avant-Poste",
                            PlayerId = 1L,
                            Type = "Building",
                            X = 1,
                            Y = 1,
                            _jsonAssets = "{\"Type\":{\"Avant-Poste\":null}}"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Avant-Poste",
                            PlayerId = 1L,
                            Type = "Building",
                            X = 6,
                            Y = 6,
                            _jsonAssets = "{\"Type\":{\"Avant-Poste\":null}}"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Village",
                            PlayerId = 1L,
                            Type = "Building",
                            X = 2,
                            Y = 3,
                            _jsonAssets = "{\"Type\":{\"Village\":null}}"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Village",
                            PlayerId = 1L,
                            Type = "Building",
                            X = 3,
                            Y = 6,
                            _jsonAssets = "{\"Type\":{\"Village\":null}}"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Village",
                            PlayerId = 1L,
                            Type = "Building",
                            X = 5,
                            Y = 2,
                            _jsonAssets = "{\"Type\":{\"Village\":null}}"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Village",
                            PlayerId = 1L,
                            Type = "Building",
                            X = 6,
                            Y = 5,
                            _jsonAssets = "{\"Type\":{\"Village\":null}}"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Entrée",
                            PlayerId = 2L,
                            Type = "Building",
                            X = 0,
                            Y = 3,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Entrée",
                            PlayerId = 2L,
                            Type = "Building",
                            X = 0,
                            Y = 4,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Entrée",
                            PlayerId = 2L,
                            Type = "Building",
                            X = 0,
                            Y = 5,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Entrée",
                            PlayerId = 2L,
                            Type = "Building",
                            X = 0,
                            Y = 6,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Entrée",
                            PlayerId = 3L,
                            Type = "Building",
                            X = 3,
                            Y = 0,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Entrée",
                            PlayerId = 3L,
                            Type = "Building",
                            X = 4,
                            Y = 0,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Entrée",
                            PlayerId = 3L,
                            Type = "Building",
                            X = 5,
                            Y = 0,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Entrée",
                            PlayerId = 3L,
                            Type = "Building",
                            X = 6,
                            Y = 0,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Entrée",
                            PlayerId = 4L,
                            Type = "Building",
                            X = 2,
                            Y = 8,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Entrée",
                            PlayerId = 4L,
                            Type = "Building",
                            X = 3,
                            Y = 8,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Entrée",
                            PlayerId = 4L,
                            Type = "Building",
                            X = 4,
                            Y = 8,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Entrée",
                            PlayerId = 4L,
                            Type = "Building",
                            X = 5,
                            Y = 8,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Entrée",
                            PlayerId = 5L,
                            Type = "Building",
                            X = 8,
                            Y = 2,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Entrée",
                            PlayerId = 5L,
                            Type = "Building",
                            X = 8,
                            Y = 3,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Entrée",
                            PlayerId = 5L,
                            Type = "Building",
                            X = 8,
                            Y = 4,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Entrée",
                            PlayerId = 5L,
                            Type = "Building",
                            X = 8,
                            Y = 5,
                            _jsonAssets = "{\"Type\":{\"Entr\\u00E9e\":null}}"
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Admin",
                            Password = "$2a$11$0cCo4Ciq8/0QZszDtAkP.eK969i/yEeK0bLIU3Tr8Zrut/BxkT5wS",
                            Role = 1
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Dragon",
                            Password = "$2a$11$1lokWFVxSB.CnBrMpKlFNOnKJm5w04ZCgEX4SBRyz83OYXU7XOqla",
                            Role = 0
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Grue",
                            Password = "$2a$11$A8cdb6KPnCYxTdEz42jzZ.UOCNlF/9jMg/KuVf6Dm0DdoFUU2N1Bu",
                            Role = 0
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Lion",
                            Password = "$2a$11$i3YhcWnD0DFn9mq/geDUD.XBqvWGqb1kn/7nJtPxFeX3vfxc3w8Ie",
                            Role = 0
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Scorpion",
                            Password = "$2a$11$.B24rVXy6wHIdKC1uF49dOzem5wFa4nFbD3PumlzAaXDnmhP67T6O",
                            Role = 0
                        });
                });

            modelBuilder.Entity("Entities.Models.ActionType", b =>
                {
                    b.HasOne("Entities.Models.Game", "Game")
                        .WithMany("ActionTypes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Campaign", b =>
                {
                    b.HasOne("Entities.Models.Game", "Game")
                        .WithMany("Campaigns")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Map", b =>
                {
                    b.HasOne("Entities.Models.Campaign", "Campaign")
                        .WithMany("Maps")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Player", "Player")
                        .WithMany("Maps")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.MapTile", b =>
                {
                    b.HasOne("Entities.Models.Map", "Map")
                        .WithMany("MapTiles")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Message", b =>
                {
                    b.HasOne("Entities.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Player", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.HasOne("Entities.Models.ActionType", "ActionType")
                        .WithMany("Orders")
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.OrdersSheet", "OrdersSheet")
                        .WithMany("Orders")
                        .HasForeignKey("OrdersSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.OrdersSheet", b =>
                {
                    b.HasOne("Entities.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Player", b =>
                {
                    b.HasOne("Entities.Models.Campaign", "Campaign")
                        .WithMany("Players")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Unit", b =>
                {
                    b.HasOne("Entities.Models.Player", "Player")
                        .WithMany("Units")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
